{
  "hash": "2b37b3c8c633138a2aeb0a4542621b70",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1\"\nauthor: \"Jiang Yuxi\"\ndate: \"May 22, 2026\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# 1 Overview\n\n## 1.1 Background\n\nUsing a real-world open-access motor vehicle insurance portfolio dataset and appropriate visual analytics libraries in R, this applied visual anaytics investigation requires you to demonstrate the potential value of visual analytics techniques for exploring and analysing numerical, categorical, and temporal variables. The objective is to gain deeper insights into data distributions and identifying key factors influencing the profitability and volatility of the insurance portfolio.\n\n## 1.2 The Task\n\nThe specific tasks of this study are:\n\nApply suitable univariate visual analytics techniques to explore the distributions and characteristics of numerical and categorical variables.\n\nApply suitable bivariate visual analytics techniques to investigate and statistically validate factors influencing the profitability and volatility of the insurance portfolio.\n\n# 2 Getting Started\n\n## 2.1 Loading Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(ggrepel, patchwork, \n               ggthemes, hrbrthemes,\n               tidyverse, readr, ggdist, \n               ggridges, colorspace, knitr, \n               forcats, reshape2, png, grid, skimr) \n```\n:::\n\n\n## 2.2 Data Sources\n\nA real world motor vehicle insurance portfolio data set from a Spanish insurance company specialised in non-life insurance will be used in this study. The data set and its cookbook are available for download at Mendeley Data.\n\n# 3 Data Wrangling\n\n## 3.1 Importing and Inspecting Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio <- read_delim(\"data/Dataset of motor insurance portfolio.csv\", delim = \";\")\nglimpse(portfolio)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\n## 3.2 Cleaning and Standardization\n\n### 3.2.1 Data Type Conversion\n\nConvert categorical variables (policy_type, fuel_type, etc.) into factors.\n\n| Variable | Data Type | Reason |\n|---------------------|-------------------|---------------------------------|\n| insured_id | integer | Unique identifier, sequential ID. |\n| year | integer | Calendar year, discrete not continuous. |\n| policy_type | factor | Categorical (COMP_E, COMP_N, TP, etc.). |\n| policy_status | factor | Categorical (A = active, C = cancelled). |\n| business_type | factor | Categorical (NB = new business, P = portfolio). |\n| payment_frequency | factor | Categorical (A, S, Q). |\n| bonus_score | factor | Categorical (G, N, B). |\n| driver_age | integer | Age in years. |\n| vehicle_age | integer | Age in years. |\n| age_driving_licence | integer | Year of licence issuance (discrete year). |\n| fuel_type | factor | Categorical (D = diesel, G = gasoline). |\n| vehicle_value | numeric | Continuous monetary value. |\n| seats | integer | Count of seats. |\n| power_to_weight_ratio | numeric | Continuous ratio. |\n| vehicle_brand | factor | Categorical brand names. |\n| municipality_type | factor | Categorical (I, C, IS). |\n| circulation_area | factor | Categorical (U, R). |\n| \\**Premiums (all \\_premium)* | numeric | Continuous monetary values. |\n| \\**Claims (all \\_claims)* | integer | Count of claims (discrete). |\n| \\**Incurred (all \\_incurred)* | numeric | Continuous monetary values. |\n| \\**Exposure (all \\_exposure)* | numeric | Continuous, fractional values (0–1 or \\>1). |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio <- portfolio %>%\n  mutate(\n    # columns → integer\n    insured_id = as.integer(insured_id),\n    year = as.integer(year),\n    driver_age = as.integer(driver_age),\n    vehicle_age = as.integer(vehicle_age),\n    age_driving_licence = as.integer(age_driving_licence),\n    seats = as.integer(seats),\n    total_claims = as.integer(total_claims),\n    liability_claims = as.integer(liability_claims),\n    liability_property_claims = as.integer(liability_property_claims),\n    liability_injury_claims = as.integer(liability_injury_claims),\n    property_claims = as.integer(property_claims),\n    theft_claims = as.integer(theft_claims),\n    fire_claims = as.integer(fire_claims),\n    glass_claims = as.integer(glass_claims),\n    legal_protection_claims = as.integer(legal_protection_claims),\n    occupants_claims = as.integer(occupants_claims),\n    \n    # columns → factor\n    policy_type = factor(policy_type),\n    policy_status = factor(policy_status),\n    business_type = factor(business_type),\n    payment_frequency = factor(payment_frequency),\n    bonus_score = factor(bonus_score),\n    vehicle_brand = factor(vehicle_brand),\n    fuel_type = factor(fuel_type),\n    municipality_type = factor(municipality_type),\n    circulation_area = factor(circulation_area)\n  )\n```\n:::\n\n\n### 3.2.2 Consistency\n\nEnsure numeric columns (e.g., vehicle_value, total_premium) are properly parsed as numeric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(portfolio, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 insured_id                        year \n                  \"integer\"                   \"integer\" \n                policy_type               policy_status \n                   \"factor\"                    \"factor\" \n              business_type           payment_frequency \n                   \"factor\"                    \"factor\" \n                bonus_score                  driver_age \n                   \"factor\"                   \"integer\" \n                vehicle_age         age_driving_licence \n                  \"integer\"                   \"integer\" \n                  fuel_type               vehicle_value \n                   \"factor\"                   \"numeric\" \n                      seats       power_to_weight_ratio \n                  \"integer\"                   \"numeric\" \n              vehicle_brand           municipality_type \n                   \"factor\"                    \"factor\" \n           circulation_area               total_premium \n                   \"factor\"                   \"numeric\" \n          liability_premium     property_damage_premium \n                  \"numeric\"                   \"numeric\" \n              theft_premium                fire_premium \n                  \"numeric\"                   \"numeric\" \n              glass_premium    legal_protection_premium \n                  \"numeric\"                   \"numeric\" \n          occupants_premium                total_claims \n                  \"numeric\"                   \"integer\" \n           liability_claims   liability_property_claims \n                  \"integer\"                   \"integer\" \n    liability_injury_claims             property_claims \n                  \"integer\"                   \"integer\" \n               theft_claims                 fire_claims \n                  \"integer\"                   \"integer\" \n               glass_claims     legal_protection_claims \n                  \"integer\"                   \"integer\" \n           occupants_claims              total_incurred \n                  \"integer\"                   \"numeric\" \n         liability_incurred liability_property_incurred \n                  \"numeric\"                   \"numeric\" \n  liability_injury_incurred           property_incurred \n                  \"numeric\"                   \"numeric\" \n             theft_incurred               fire_incurred \n                  \"numeric\"                   \"numeric\" \n             glass_incurred   legal_protection_incurred \n                  \"numeric\"                   \"numeric\" \n         occupants_incurred              total_exposure \n                  \"numeric\"                   \"numeric\" \n         liability_exposure \n                  \"numeric\" \n```\n\n\n:::\n:::\n\n\n### 3.2.3 Check for Duplicates and Missing values\n\nIdentify with is.na() or skimr::skim(). Decide whether to impute, drop, or flag.\n\nThe below code chunk is used to check whether an entire row (all columns) is repeated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio[duplicated(portfolio),]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 47\n# ℹ 47 variables: insured_id <int>, year <int>, policy_type <fct>,\n#   policy_status <fct>, business_type <fct>, payment_frequency <fct>,\n#   bonus_score <fct>, driver_age <int>, vehicle_age <int>,\n#   age_driving_licence <int>, fuel_type <fct>, vehicle_value <dbl>,\n#   seats <int>, power_to_weight_ratio <dbl>, vehicle_brand <fct>,\n#   municipality_type <fct>, circulation_area <fct>, total_premium <dbl>,\n#   liability_premium <dbl>, property_damage_premium <dbl>, …\n```\n\n\n:::\n:::\n\n\nNo rows in this dataset are exact duplicates across all 47 columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(portfolio))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 insured_id                        year \n                          0                           0 \n                policy_type               policy_status \n                          0                           0 \n              business_type           payment_frequency \n                          0                           0 \n                bonus_score                  driver_age \n                          0                           0 \n                vehicle_age         age_driving_licence \n                          2                           2 \n                  fuel_type               vehicle_value \n                       1287                         513 \n                      seats       power_to_weight_ratio \n                          0                           0 \n              vehicle_brand           municipality_type \n                          0                           0 \n           circulation_area               total_premium \n                          0                           0 \n          liability_premium     property_damage_premium \n                          0                           0 \n              theft_premium                fire_premium \n                          0                           0 \n              glass_premium    legal_protection_premium \n                          0                           0 \n          occupants_premium                total_claims \n                          0                           0 \n           liability_claims   liability_property_claims \n                          0                           0 \n    liability_injury_claims             property_claims \n                          0                           0 \n               theft_claims                 fire_claims \n                          0                           0 \n               glass_claims     legal_protection_claims \n                          0                           0 \n           occupants_claims              total_incurred \n                          0                           0 \n         liability_incurred liability_property_incurred \n                          0                           0 \n  liability_injury_incurred           property_incurred \n                          0                           0 \n             theft_incurred               fire_incurred \n                          0                           0 \n             glass_incurred   legal_protection_incurred \n                          0                           0 \n         occupants_incurred              total_exposure \n                          0                           0 \n         liability_exposure \n                          0 \n```\n\n\n:::\n:::\n\n\nVehicle age & Age driving licence → Only 2 missing each → you can safely drop those rows\n\nFuel type: 1,287 missing (~0.36% of dataset) → create a new category \"Unknown\" to preserve those rows.\n\nVehicle value: 513 missing (~0.15% of dataset) → use brand-specific median (e.g., median value per vehicle_brand)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio <- portfolio %>%\n  mutate(\n    # Impute vehicle_value with brand-specific median\n    vehicle_value = ifelse(is.na(vehicle_value),\n                           ave(vehicle_value, vehicle_brand,\n                               FUN = function(x) median(x, na.rm = TRUE)),\n                           vehicle_value),\n    \n    # Impute fuel_type with \"Unknown\"\n    fuel_type = fct_explicit_na(factor(fuel_type), na_level = \"Unknown\")\n  )\n\n# Drop rows with missing driver/vehicle age\nportfolio <- portfolio %>%\n  filter(!is.na(vehicle_age), !is.na(age_driving_licence))\n```\n:::\n\n\n### 3.2.4 Check for Outliers\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(portfolio)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |          |\n|:------------------------|:---------|\n|Name                     |portfolio |\n|Number of rows           |354138    |\n|Number of columns        |47        |\n|_______________________  |          |\n|Column type frequency:   |          |\n|factor                   |9         |\n|numeric                  |38        |\n|________________________ |          |\n|Group variables          |None      |\n\n\n**Variable type: factor**\n\n|skim_variable     | n_missing| complete_rate|ordered | n_unique|top_counts                                     |\n|:-----------------|---------:|-------------:|:-------|--------:|:----------------------------------------------|\n|policy_type       |         0|             1|FALSE   |        5|CC: 204635, COM: 91199, TPG: 36367, COM: 16180 |\n|policy_status     |         0|             1|FALSE   |        2|A: 315810, C: 38328                            |\n|business_type     |         0|             1|FALSE   |        2|NB: 245435, P: 108703                          |\n|payment_frequency |         0|             1|FALSE   |        3|A: 287895, S: 50847, Q: 15396                  |\n|bonus_score       |         0|             1|FALSE   |        3|G: 341557, N: 7850, B: 4731                    |\n|fuel_type         |         0|             1|FALSE   |        3|D: 226400, G: 126451, Unk: 1287                |\n|vehicle_brand     |         0|             1|FALSE   |       68|REN: 34354, CIT: 32489, PEU: 29574, VOL: 28790 |\n|municipality_type |         0|             1|FALSE   |        3|I: 228615, C: 101383, IS: 24140                |\n|circulation_area  |         0|             1|FALSE   |        2|U: 190506, R: 163632                           |\n\n\n**Variable type: numeric**\n\n|skim_variable               | n_missing| complete_rate|     mean|       sd|      p0|      p25|      p50|       p75|      p100|hist  |\n|:---------------------------|---------:|-------------:|--------:|--------:|-------:|--------:|--------:|---------:|---------:|:-----|\n|insured_id                  |         0|             1| 76044.36| 51272.32|    1.00| 33342.00| 66840.00| 112948.75| 185678.00|▇▇▆▃▃ |\n|year                        |         0|             1|  2023.29|     0.76| 2022.00|  2023.00|  2023.00|   2024.00|   2024.00|▃▁▆▁▇ |\n|driver_age                  |         0|             1|    49.01|    12.07|   18.00|    39.00|    48.00|     58.00|     90.00|▂▇▇▃▁ |\n|vehicle_age                 |         0|             1|    25.92|    11.62|    0.00|    17.00|    25.00|     35.00|     68.00|▃▇▆▂▁ |\n|age_driving_licence         |         0|             1|    22.99|     6.36|    0.00|    19.00|    20.00|     25.00|     80.00|▁▇▁▁▁ |\n|vehicle_value               |         1|             1| 26985.07| 12325.29| 1630.12| 18607.58| 24741.66|  32266.26| 374034.21|▇▁▁▁▁ |\n|seats                       |         0|             1|     5.08|     0.76|    2.00|     5.00|     5.00|      5.00|      9.00|▁▁▇▁▁ |\n|power_to_weight_ratio       |         0|             1|    12.33|     2.48|    0.00|    10.74|    12.05|     13.73|     64.81|▇▅▁▁▁ |\n|total_premium               |         0|             1|   296.72|   227.85|    0.00|   146.15|   257.90|    384.98|   5107.64|▇▁▁▁▁ |\n|liability_premium           |         0|             1|   180.71|   129.72|    0.00|    92.52|   165.78|    237.83|   2320.77|▇▁▁▁▁ |\n|property_damage_premium     |         0|             1|    73.51|   155.80|    0.00|     0.00|     0.00|     83.62|   3736.73|▇▁▁▁▁ |\n|theft_premium               |         0|             1|    11.25|    19.00|    0.00|     1.81|     5.90|     13.52|   1047.04|▇▁▁▁▁ |\n|fire_premium                |         0|             1|     1.51|     2.25|    0.00|     0.29|     0.86|      1.82|     72.09|▇▁▁▁▁ |\n|glass_premium               |         0|             1|    19.50|    16.93|    0.00|     7.42|    15.39|     26.91|    387.61|▇▁▁▁▁ |\n|legal_protection_premium    |         0|             1|     8.27|     6.04|    0.00|     3.82|     7.26|     10.97|    175.06|▇▁▁▁▁ |\n|occupants_premium           |         0|             1|     1.97|     1.32|    0.00|     0.94|     1.83|      2.62|     68.65|▇▁▁▁▁ |\n|total_claims                |         0|             1|     0.22|     0.66|    0.00|     0.00|     0.00|      0.00|     18.00|▇▁▁▁▁ |\n|liability_claims            |         0|             1|     0.11|     0.38|    0.00|     0.00|     0.00|      0.00|      8.00|▇▁▁▁▁ |\n|liability_property_claims   |         0|             1|     0.09|     0.32|    0.00|     0.00|     0.00|      0.00|      8.00|▇▁▁▁▁ |\n|liability_injury_claims     |         0|             1|     0.01|     0.12|    0.00|     0.00|     0.00|      0.00|      3.00|▇▁▁▁▁ |\n|property_claims             |         0|             1|     0.06|     0.42|    0.00|     0.00|     0.00|      0.00|     15.00|▇▁▁▁▁ |\n|theft_claims                |         0|             1|     0.01|     0.07|    0.00|     0.00|     0.00|      0.00|      2.00|▇▁▁▁▁ |\n|fire_claims                 |         0|             1|     0.00|     0.02|    0.00|     0.00|     0.00|      0.00|      1.00|▇▁▁▁▁ |\n|glass_claims                |         0|             1|     0.03|     0.18|    0.00|     0.00|     0.00|      0.00|      3.00|▇▁▁▁▁ |\n|legal_protection_claims     |         0|             1|     0.01|     0.10|    0.00|     0.00|     0.00|      0.00|      2.00|▇▁▁▁▁ |\n|occupants_claims            |         0|             1|     0.00|     0.01|    0.00|     0.00|     0.00|      0.00|      1.00|▇▁▁▁▁ |\n|total_incurred              |         0|             1|   208.57|  2274.72|    0.00|     0.00|     0.00|      0.00| 571128.32|▇▁▁▁▁ |\n|liability_incurred          |         0|             1|   133.70|  2120.43|    0.00|     0.00|     0.00|      0.00| 561759.79|▇▁▁▁▁ |\n|liability_property_incurred |         0|             1|    65.74|   406.86|    0.00|     0.00|     0.00|      0.00|  34553.88|▇▁▁▁▁ |\n|liability_injury_incurred   |         0|             1|    67.96|  2031.22|    0.00|     0.00|     0.00|      0.00| 560025.59|▇▁▁▁▁ |\n|property_incurred           |         0|             1|    52.66|   420.99|    0.00|     0.00|     0.00|      0.00|  27542.43|▇▁▁▁▁ |\n|theft_incurred              |         0|             1|     4.51|   193.74|    0.00|     0.00|     0.00|      0.00|  40324.89|▇▁▁▁▁ |\n|fire_incurred               |         0|             1|     0.76|    82.03|    0.00|     0.00|     0.00|      0.00|  28267.13|▇▁▁▁▁ |\n|glass_incurred              |         0|             1|    12.59|    83.80|    0.00|     0.00|     0.00|      0.00|   4533.40|▇▁▁▁▁ |\n|legal_protection_incurred   |         0|             1|     3.32|    59.97|    0.00|     0.00|     0.00|      0.00|   9889.85|▇▁▁▁▁ |\n|occupants_incurred          |         0|             1|     1.01|   201.06|    0.00|     0.00|     0.00|      0.00|  69000.00|▇▁▁▁▁ |\n|total_exposure              |         0|             1|     0.71|     0.33|    0.00|     0.44|     0.84|      1.00|      1.00|▂▂▂▂▇ |\n|liability_exposure          |         0|             1|     0.71|     0.33|    0.00|     0.44|     0.84|      1.00|      1.00|▂▂▂▂▇ |\n\n\n:::\n:::\n\n\n## 3.3 Reshape (Unpivot)\n\nKeep identifiers and descriptors (insured_id, year, policy_type, driver_age, etc.) wide.\n\nUnpivot Premiums into Premium_Type + Premium_Value.\n\nUnpivot Claims into Claim_Type + Claim_Count.\n\nUnpivot Incurred into Incurred_Type + Incurred_Value.\n\nUnpivot Exposure into Exposure_Type + Exposure_Value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio_l <- portfolio %>%\n  pivot_longer(\n    cols = matches(\"_premium$|_claims$|_incurred$|_exposure$\"),\n    names_to = \"Metric_Type\",\n    values_to = \"Value\"\n  ) %>%\n  mutate(\n    Metric_Group = case_when(\n      grepl(\"premium\", Metric_Type) ~ \"Premiums\",\n      grepl(\"claims\", Metric_Type) ~ \"Claims\",\n      grepl(\"incurred\", Metric_Type) ~ \"Incurred\",\n      grepl(\"exposure\", Metric_Type) ~ \"Exposure\"\n    )\n  )\n\nhead(portfolio_l)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 20\n  insured_id  year policy_type policy_status business_type payment_frequency\n       <int> <int> <fct>       <fct>         <fct>         <fct>            \n1          1  2022 COMP_E      C             NB            A                \n2          1  2022 COMP_E      C             NB            A                \n3          1  2022 COMP_E      C             NB            A                \n4          1  2022 COMP_E      C             NB            A                \n5          1  2022 COMP_E      C             NB            A                \n6          1  2022 COMP_E      C             NB            A                \n# ℹ 14 more variables: bonus_score <fct>, driver_age <int>, vehicle_age <int>,\n#   age_driving_licence <int>, fuel_type <fct>, vehicle_value <dbl>,\n#   seats <int>, power_to_weight_ratio <dbl>, vehicle_brand <fct>,\n#   municipality_type <fct>, circulation_area <fct>, Metric_Type <chr>,\n#   Value <dbl>, Metric_Group <chr>\n```\n\n\n:::\n:::\n\n\n## 3.4 Recoding\n\nCreate ratios: e.g., claims_per_exposure = total_claims / total_exposure.\n\nDerive flags: e.g., has_claim = ifelse(total_claims \\> 0, 1, 0).\n\nNormalize monetary values (premiums, incurred) by exposure to get comparable risk measures.\n\nBucket ages (driver_age, vehicle_age) into categories for actuarial modeling.\n\n# 4 Exploratory Data Analysis - Univariate\n\nApply suitable univariate visual analytics techniques to explore the distributions and characteristics of numerical and categorical variables.\n\n# 5 Exploratory Data Analysis - Bivariate\n\nApply suitable bivariate visual analytics techniques to investigate and statistically validate factors influencing the profitability and volatility of the insurance portfolio.\n\n# 6 Summary\n\n# 7 References and Inspiration\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}